#include <iostream>
#include <conio.h>
#include <math.h>
using namespace std;

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

int main()
{
    int a=1;
    int b=2;
    int c;
    int sum=2;

    do
    {   c = a+b;
        sum = c%2==0?sum+c:sum;
        a=b;
        b=c;

    }
    while (c<4000000);
    cout << sum <<endl;
    getch();
    return 0;

}